services:
  mysql:
    image: mysql
    ports:
      - 33063:3306
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - mvcnet
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

networks:
  mvcnet:
    driver: bridge
    attachable: true