version: '3.4'

services:

  webapplicationmvc:
    image: ${DOCKER_REGISTRY-}webapplicationmvc
    build:
      context: .
      dockerfile: WebApplicationMVC/Dockerfile
    container_name: webapp
    networks:
      - mvcnet
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - 33064:3306
    environment:
      - MYSQL_ROOT_PASSWORD=homer171
    container_name: mysqldb
    networks:
      - mvcnet
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

networks:
  mvcnet:
    driver: bridge
    attachable: true