version: '3.4'

services:

  webapplicationmvc:
    container_name: webapp
    image: ${DOCKER_REGISTRY-}webapplicationmvc
    build:
      context: .
      dockerfile: WebApplicationMVC/Dockerfile
    networks:
      - mvcnet
    depends_on:
      - mysql
    environment:
      DBHOST: mysql

  mysql:
    container_name: mysqldb
    image: mysql
    ports:
      - 33064:3306
    environment:
      MYSQL_ROOT_PASSWORD: homer171
      MYSQL_DATABASE: WebApplicationmvcdb
    networks:
      - mvcnet
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

networks:
  mvcnet:
    driver: bridge